config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'

  root 'todos#index'
  resources :todos do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/priority.rb
class Priority < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '高' },
    { id: 3, name: '中' },
    { id: 4, name: '低' }
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '未着手' },
    { id: 3, name: '着手中' },
    { id: 4, name: '完了' }
  ]
end

app/models/todo.rb
class Todo < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  validates :name, presence: true
  validates :status_id, numericality: { greater_than_or_equal_to: 2, message: 'を選択してください' }
  validates :priority_id, numericality: { greater_than_or_equal_to: 2, message: 'を選択してください' }
  validates :deadline, presence: true

  belongs_to :user
  belongs_to_active_hash :status
  belongs_to_active_hash :priority
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    return if logged_in?

    redirect_to login_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:session).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :logged_in_user
  before_action :set_todo, only: %i(show edit update destroy)
  def index
    @todos = Todo.where(user: current_user).order(deadline: :asc)
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @todo.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @todos = Todo.where(user: current_user)
    @todos = @todos.where('name LIKE ?', "%#{params[:name]}%") unless params[:name].nil?
    @todos = @todos.where(status_id: params[:status_id]) unless params[:status_id] == '1'
    @todos = @todos.where(priority_id: params[:priority_id]) unless params[:priority_id] == '1'
    render :index
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :description, :deadline, :status_id, :priority_id).merge(user_id: current_user.id)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    return unless session[:user_id]

    # @current_user = @current_user || User.find_by(id: session[:user_id])と同じ意味
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # 受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_error_messages.html.slim
- if model.errors.any? 
  .alert
    ul
      - model.errors.full_messages.each do |message| 
        li= message

app/views/layouts/_header.html.slim
header.bg-secondary
  .container
    h1.text-center.text-white.
      .row
        .col
          = link_to "Todo7", root_path, class: "text-white"
        - if logged_in?
          .col.row
            .col.d-flex.align-items-center
                h3.text-dark= current_user.name
            .col
              = button_to "logout", logout_path, method: :delete, class: "btn btn-danger"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Task7
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    link href="https://unpkg.com/sanitize.css" rel="stylesheet"
    link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" rel="stylesheet" /
  body
    = render partial: 'layouts/header'
    .main-content.bg-light
      = yield

app/views/todos/_form.html.slim
= form_with url: path, model: todo, local: true do |form|
  = render 'layouts/error_messages', model: form.object
  .mb-3
    = form.label :name, class: "form-label"
    = form.text_field :name, placeholder: "名前を入力してください。", class: "form-control"
  .mb-3
    = form.label :description, class: "form-label"
    = form.text_area :description, placeholder: "説明文を入力してください。", class: "form-control"

  .mb-3
    = form.label :status, class: "form-label"
    = form.collection_select(:status_id, Status.all, :id, :name, class: "form-control")
  .mb-3
    = form.label :priority, class: "form-label"
    = form.collection_select(:priority_id, Priority.all, :id, :name, class: "form-control")
  .mb-3
    = form.label :deadline, class: "form-label"
    = form.datetime_field :deadline, class: 'form-control'
  = form.submit "投稿", class: "btn btn-primary"

app/views/todos/edit.html.slim
.container
  h1
    |編集
  = render partial: 'form', locals: { todo: @todo, path: todo_path }

app/views/todos/index.html.slim
.container
  .row
    .col
      h1
        |一覧表示
    .col
      = link_to "新規作成", new_todo_path, class: "btn btn-success"
    .col-xl-6.bg-dark.p-2.text-white.mb-3
      = form_with url: search_todos_path, local: true, method: :get do |form|
        .row
          .col.d-flex.align-items-center.justify-content-center
            = form.label :name, class: "form-label"
            = form.text_field :name
          .col-2.d-flex.align-items-center.justify-content-center
            = form.label :status, class: "form-label"
            = form.collection_select(:status_id, Status.all, :id, :name, class: "form-control")
          .col-2.d-flex.align-items-center.justify-content-center
            = form.label :priority, class: "form-label"
            = form.collection_select(:priority_id, Priority.all, :id, :name, class: "form-control")
          .col-2.d-flex.align-items-center.justify-content-center
            = form.submit "検索", class: "btn btn-info"

  .row 
    - @todos.each do |todo|
      .col-xl-6.mb-3
        .todo.card.border-secondary
          .card-header
            .row

              .me-2.col-3
                - case todo.status_id 
                - when 2
                  .badge.bg-danger.me-3
                    = todo.status.name
                - when 3
                  .badge.bg-warning.text-dark.me-3
                    = todo.status.name
                - when 4
                  .badge.bg-success.me-3
                    = todo.status.name

                - case todo.priority_id 
                - when 2
                  .badge.bg-danger
                    = todo.priority.name
                - when 3
                  .badge.bg-warning.text-dark
                    = todo.priority.name
                - when 4
                  .badge.bg-success
                    = todo.priority.name

              .col
                strong= todo.name

              .col-4.text-center
                = link_to "詳細", todo_path(todo[:id]), class:"btn btn-info btn-sm"
          .card-body
            .card-text
              p= todo.description
              p= "期限：#{todo.deadline.strftime('%Y/%m/%d %H:%M')}"
            

app/views/todos/new.html.slim
.container 
  h1 
    |新規投稿
  = render partial: 'form', locals: { todo: @todo, path: todos_path }

app/views/todos/show.html.slim
.container
  .row
    .col
      h1
        |詳細表示
    .col.row
      .col
        = link_to "編集", edit_todo_path, class: "btn btn-warning"
      .col
        = button_to "削除", todo_path(@todo.id), method: :delete, class: "btn btn-danger"
  table.table
    thead 
      tr 
        th="項目名"
        th="詳細"
    tbody 
      tr 
        th="名前"
        td = @todo.name
      tr 
        th="説明文"
        td = @todo.description
      tr 
        th="進捗"
        td = @todo.status.name
      tr 
        th="優先度"
        td = @todo.priority.name
      tr 
        th="期限"
        td = @todo.deadline.strftime('%Y/%m/%d %H:%M')